#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_let = 2,
  anon_sym_EQ = 3,
  anon_sym_return = 4,
  anon_sym_if = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_else = 10,
  sym_identifier = 11,
  anon_sym_LBRACK = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACK = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  anon_sym_fn = 17,
  anon_sym_true = 18,
  anon_sym_false = 19,
  anon_sym_DASH = 20,
  anon_sym_PLUS = 21,
  anon_sym_STAR = 22,
  anon_sym_SLASH = 23,
  anon_sym_GT = 24,
  anon_sym_LT = 25,
  anon_sym_EQ_EQ = 26,
  anon_sym_BANG_EQ = 27,
  sym_integer = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym_let_statement = 31,
  sym_return_statement = 32,
  sym_if_expression = 33,
  sym_condition = 34,
  sym_consequence = 35,
  sym_alternative = 36,
  sym_call = 37,
  sym_array = 38,
  sym_string = 39,
  sym_function = 40,
  sym_function_body = 41,
  sym_parameter_list = 42,
  sym_argument_list = 43,
  sym__expression = 44,
  sym_boolean = 45,
  sym_unary_operator = 46,
  sym_binary_operator = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_array_repeat1 = 49,
  aux_sym_parameter_list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_fn] = "fn",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_return_statement] = "return_statement",
  [sym_if_expression] = "if_expression",
  [sym_condition] = "condition",
  [sym_consequence] = "consequence",
  [sym_alternative] = "alternative",
  [sym_call] = "call",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_function] = "function",
  [sym_function_body] = "function_body",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym__expression] = "_expression",
  [sym_boolean] = "boolean",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_if_expression] = sym_if_expression,
  [sym_condition] = sym_condition,
  [sym_consequence] = sym_consequence,
  [sym_alternative] = sym_alternative,
  [sym_call] = sym_call,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_function] = sym_function,
  [sym_function_body] = sym_function_body,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym__expression] = sym__expression,
  [sym_boolean] = sym_boolean,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_consequence] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 42},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 42},
  [89] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(81),
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(64),
    [sym_return_statement] = STATE(64),
    [sym_if_expression] = STATE(64),
    [sym_call] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_function] = STATE(25),
    [sym__expression] = STATE(25),
    [sym_boolean] = STATE(25),
    [sym_unary_operator] = STATE(25),
    [sym_binary_operator] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
  },
  [2] = {
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(64),
    [sym_return_statement] = STATE(64),
    [sym_if_expression] = STATE(64),
    [sym_call] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_function] = STATE(25),
    [sym__expression] = STATE(25),
    [sym_boolean] = STATE(25),
    [sym_unary_operator] = STATE(25),
    [sym_binary_operator] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_return] = ACTIONS(30),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_identifier] = ACTIONS(36),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(42),
    [anon_sym_fn] = ACTIONS(45),
    [anon_sym_true] = ACTIONS(48),
    [anon_sym_false] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(51),
    [sym_integer] = ACTIONS(54),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [54] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [108] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [162] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [216] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [270] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [324] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [378] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [432] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(64), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(25), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [486] = 4,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_argument_list,
    ACTIONS(77), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [519] = 2,
    ACTIONS(83), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [546] = 2,
    ACTIONS(87), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(85), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [573] = 2,
    ACTIONS(91), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(89), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [600] = 2,
    ACTIONS(95), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [627] = 2,
    ACTIONS(99), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [654] = 2,
    ACTIONS(103), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [681] = 2,
    ACTIONS(107), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [708] = 2,
    ACTIONS(111), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(109), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [735] = 2,
    ACTIONS(115), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(113), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [762] = 3,
    ACTIONS(117), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(119), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [791] = 2,
    ACTIONS(125), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [818] = 2,
    ACTIONS(129), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(127), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [845] = 4,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(135), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [875] = 3,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(139), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [903] = 3,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(143), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [931] = 4,
    ACTIONS(145), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_argument_list,
    ACTIONS(77), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [960] = 10,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(152), 1,
      anon_sym_LBRACK,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      anon_sym_fn,
    ACTIONS(164), 1,
      anon_sym_DASH,
    ACTIONS(167), 1,
      sym_integer,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(147), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(161), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1000] = 4,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(172), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(170), 5,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(176), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1027] = 2,
    ACTIONS(91), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(89), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1050] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    STATE(45), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1089] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1128] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(196), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1167] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1206] = 2,
    ACTIONS(115), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(113), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1229] = 2,
    ACTIONS(95), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1252] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1291] = 2,
    ACTIONS(99), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1314] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1353] = 2,
    ACTIONS(83), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1376] = 2,
    ACTIONS(107), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1399] = 2,
    ACTIONS(103), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1422] = 2,
    ACTIONS(87), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(85), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1445] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1484] = 10,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      sym_integer,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1523] = 2,
    ACTIONS(129), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(127), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1546] = 2,
    ACTIONS(111), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(109), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1569] = 2,
    ACTIONS(125), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1592] = 3,
    ACTIONS(119), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(117), 6,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(176), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1617] = 8,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(208), 1,
      sym_integer,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1650] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(210), 1,
      sym_integer,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(67), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1683] = 4,
    ACTIONS(216), 1,
      anon_sym_else,
    STATE(61), 1,
      sym_alternative,
    ACTIONS(212), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(214), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1708] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(218), 1,
      sym_integer,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1741] = 8,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_fn,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(220), 1,
      sym_integer,
    ACTIONS(188), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1774] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(222), 1,
      sym_integer,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1807] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(224), 1,
      sym_integer,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1840] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(226), 1,
      sym_integer,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 8,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1873] = 2,
    ACTIONS(228), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(230), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1893] = 2,
    ACTIONS(232), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(234), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1913] = 2,
    ACTIONS(236), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(238), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1932] = 2,
    ACTIONS(240), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(242), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1951] = 2,
    ACTIONS(244), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(246), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1970] = 3,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(135), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1991] = 2,
    ACTIONS(248), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(250), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [2009] = 2,
    ACTIONS(252), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(147), 6,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
  [2024] = 2,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    ACTIONS(121), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2038] = 3,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(258), 1,
      sym_identifier,
    STATE(68), 1,
      aux_sym_parameter_list_repeat1,
  [2048] = 3,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    ACTIONS(263), 1,
      sym_identifier,
    STATE(70), 1,
      aux_sym_parameter_list_repeat1,
  [2058] = 3,
    ACTIONS(263), 1,
      sym_identifier,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_parameter_list_repeat1,
  [2068] = 2,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(267), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2076] = 2,
    ACTIONS(271), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_function_body,
  [2083] = 1,
    ACTIONS(256), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2088] = 2,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_parameter_list,
  [2095] = 2,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
    STATE(78), 1,
      sym_parameter_list,
  [2102] = 2,
    ACTIONS(275), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_condition,
  [2109] = 2,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_consequence,
  [2116] = 2,
    ACTIONS(279), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_function_body,
  [2123] = 1,
    ACTIONS(281), 1,
      anon_sym_LBRACE,
  [2127] = 1,
    ACTIONS(283), 1,
      anon_sym_DQUOTE,
  [2131] = 1,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
  [2135] = 1,
    ACTIONS(287), 1,
      aux_sym_string_token1,
  [2139] = 1,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
  [2143] = 1,
    ACTIONS(291), 1,
      anon_sym_EQ,
  [2147] = 1,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [2151] = 1,
    ACTIONS(295), 1,
      sym_identifier,
  [2155] = 1,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
  [2159] = 1,
    ACTIONS(299), 1,
      aux_sym_string_token1,
  [2163] = 1,
    ACTIONS(301), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 162,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 324,
  [SMALL_STATE(10)] = 378,
  [SMALL_STATE(11)] = 432,
  [SMALL_STATE(12)] = 486,
  [SMALL_STATE(13)] = 519,
  [SMALL_STATE(14)] = 546,
  [SMALL_STATE(15)] = 573,
  [SMALL_STATE(16)] = 600,
  [SMALL_STATE(17)] = 627,
  [SMALL_STATE(18)] = 654,
  [SMALL_STATE(19)] = 681,
  [SMALL_STATE(20)] = 708,
  [SMALL_STATE(21)] = 735,
  [SMALL_STATE(22)] = 762,
  [SMALL_STATE(23)] = 791,
  [SMALL_STATE(24)] = 818,
  [SMALL_STATE(25)] = 845,
  [SMALL_STATE(26)] = 875,
  [SMALL_STATE(27)] = 903,
  [SMALL_STATE(28)] = 931,
  [SMALL_STATE(29)] = 960,
  [SMALL_STATE(30)] = 1000,
  [SMALL_STATE(31)] = 1027,
  [SMALL_STATE(32)] = 1050,
  [SMALL_STATE(33)] = 1089,
  [SMALL_STATE(34)] = 1128,
  [SMALL_STATE(35)] = 1167,
  [SMALL_STATE(36)] = 1206,
  [SMALL_STATE(37)] = 1229,
  [SMALL_STATE(38)] = 1252,
  [SMALL_STATE(39)] = 1291,
  [SMALL_STATE(40)] = 1314,
  [SMALL_STATE(41)] = 1353,
  [SMALL_STATE(42)] = 1376,
  [SMALL_STATE(43)] = 1399,
  [SMALL_STATE(44)] = 1422,
  [SMALL_STATE(45)] = 1445,
  [SMALL_STATE(46)] = 1484,
  [SMALL_STATE(47)] = 1523,
  [SMALL_STATE(48)] = 1546,
  [SMALL_STATE(49)] = 1569,
  [SMALL_STATE(50)] = 1592,
  [SMALL_STATE(51)] = 1617,
  [SMALL_STATE(52)] = 1650,
  [SMALL_STATE(53)] = 1683,
  [SMALL_STATE(54)] = 1708,
  [SMALL_STATE(55)] = 1741,
  [SMALL_STATE(56)] = 1774,
  [SMALL_STATE(57)] = 1807,
  [SMALL_STATE(58)] = 1840,
  [SMALL_STATE(59)] = 1873,
  [SMALL_STATE(60)] = 1893,
  [SMALL_STATE(61)] = 1913,
  [SMALL_STATE(62)] = 1932,
  [SMALL_STATE(63)] = 1951,
  [SMALL_STATE(64)] = 1970,
  [SMALL_STATE(65)] = 1991,
  [SMALL_STATE(66)] = 2009,
  [SMALL_STATE(67)] = 2024,
  [SMALL_STATE(68)] = 2038,
  [SMALL_STATE(69)] = 2048,
  [SMALL_STATE(70)] = 2058,
  [SMALL_STATE(71)] = 2068,
  [SMALL_STATE(72)] = 2076,
  [SMALL_STATE(73)] = 2083,
  [SMALL_STATE(74)] = 2088,
  [SMALL_STATE(75)] = 2095,
  [SMALL_STATE(76)] = 2102,
  [SMALL_STATE(77)] = 2109,
  [SMALL_STATE(78)] = 2116,
  [SMALL_STATE(79)] = 2123,
  [SMALL_STATE(80)] = 2127,
  [SMALL_STATE(81)] = 2131,
  [SMALL_STATE(82)] = 2135,
  [SMALL_STATE(83)] = 2139,
  [SMALL_STATE(84)] = 2143,
  [SMALL_STATE(85)] = 2147,
  [SMALL_STATE(86)] = 2151,
  [SMALL_STATE(87)] = 2155,
  [SMALL_STATE(88)] = 2159,
  [SMALL_STATE(89)] = 2163,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(86),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(28),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(38),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(88),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(74),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(36),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(55),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 3),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 2),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 2),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 4),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 4),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 4),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(71),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [285] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
