#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_let = 2,
  anon_sym_EQ = 3,
  anon_sym_return = 4,
  anon_sym_if = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_else = 10,
  sym_identifier = 11,
  anon_sym_fn = 12,
  anon_sym_COMMA = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  anon_sym_DASH = 16,
  anon_sym_PLUS = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_GT = 20,
  anon_sym_LT = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_BANG_EQ = 23,
  sym_integer = 24,
  sym_source_file = 25,
  sym__statement = 26,
  sym_let_statement = 27,
  sym_return_statement = 28,
  sym_if_expression = 29,
  sym_condition = 30,
  sym_consequence = 31,
  sym_alternative = 32,
  sym_call = 33,
  sym_function = 34,
  sym_function_body = 35,
  sym_parameter_list = 36,
  sym_argument_list = 37,
  sym__expression = 38,
  sym_boolean = 39,
  sym_unary_operator = 40,
  sym_binary_operator = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_parameter_list_repeat1 = 43,
  aux_sym_argument_list_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [sym_identifier] = "identifier",
  [anon_sym_fn] = "fn",
  [anon_sym_COMMA] = ",",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_return_statement] = "return_statement",
  [sym_if_expression] = "if_expression",
  [sym_condition] = "condition",
  [sym_consequence] = "consequence",
  [sym_alternative] = "alternative",
  [sym_call] = "call",
  [sym_function] = "function",
  [sym_function_body] = "function_body",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym__expression] = "_expression",
  [sym_boolean] = "boolean",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [sym_identifier] = sym_identifier,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_if_expression] = sym_if_expression,
  [sym_condition] = sym_condition,
  [sym_consequence] = sym_consequence,
  [sym_alternative] = sym_alternative,
  [sym_call] = sym_call,
  [sym_function] = sym_function,
  [sym_function_body] = sym_function_body,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym__expression] = sym__expression,
  [sym_boolean] = sym_boolean,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_consequence] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(69),
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(50),
    [sym_return_statement] = STATE(50),
    [sym_if_expression] = STATE(50),
    [sym_call] = STATE(22),
    [sym_function] = STATE(22),
    [sym__expression] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_unary_operator] = STATE(22),
    [sym_binary_operator] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(26), 1,
      anon_sym_return,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_fn,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(44), 1,
      sym_integer,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(38), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [47] = 4,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_argument_list,
    ACTIONS(49), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [78] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [124] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [170] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [216] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [262] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [308] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [354] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [400] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [446] = 12,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_return,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_integer,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(50), 3,
      sym_let_statement,
      sym_return_statement,
      sym_if_expression,
    STATE(22), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [492] = 2,
    ACTIONS(73), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [517] = 2,
    ACTIONS(77), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [542] = 2,
    ACTIONS(81), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(79), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [567] = 2,
    ACTIONS(85), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [592] = 2,
    ACTIONS(89), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(87), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [617] = 2,
    ACTIONS(93), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [642] = 2,
    ACTIONS(97), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [667] = 3,
    ACTIONS(99), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_integer,
    ACTIONS(101), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [694] = 2,
    ACTIONS(107), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [719] = 4,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_integer,
    ACTIONS(113), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [747] = 3,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_integer,
    ACTIONS(117), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [773] = 3,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_integer,
    ACTIONS(121), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [799] = 4,
    ACTIONS(123), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_argument_list,
    ACTIONS(49), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [825] = 2,
    ACTIONS(89), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(87), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [845] = 2,
    ACTIONS(73), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(71), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [865] = 3,
    ACTIONS(99), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_integer,
    ACTIONS(101), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [887] = 2,
    ACTIONS(107), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [907] = 2,
    ACTIONS(81), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(79), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [927] = 2,
    ACTIONS(97), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [947] = 2,
    ACTIONS(77), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [967] = 4,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(127), 2,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(129), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [991] = 2,
    ACTIONS(93), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1011] = 2,
    ACTIONS(85), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1031] = 8,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(143), 1,
      sym_integer,
    STATE(37), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1062] = 8,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_DASH,
    ACTIONS(159), 1,
      sym_integer,
    STATE(37), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(153), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1093] = 8,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(143), 1,
      sym_integer,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1124] = 8,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(143), 1,
      sym_integer,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1155] = 8,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(143), 1,
      sym_integer,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1186] = 4,
    ACTIONS(172), 1,
      anon_sym_else,
    STATE(49), 1,
      sym_alternative,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(170), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1209] = 2,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(176), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1227] = 2,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(180), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1245] = 6,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(182), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1270] = 6,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1295] = 6,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(186), 1,
      sym_integer,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1320] = 6,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(188), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1345] = 6,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(190), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1370] = 2,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(194), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1387] = 3,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(113), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1406] = 2,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(198), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1423] = 6,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(200), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1448] = 2,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(204), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1465] = 6,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_fn,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(206), 1,
      sym_integer,
    ACTIONS(139), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 6,
      sym_call,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1490] = 2,
    ACTIONS(208), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(210), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1506] = 2,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1520] = 2,
    ACTIONS(145), 3,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(214), 4,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1532] = 3,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    ACTIONS(218), 1,
      sym_identifier,
    STATE(58), 1,
      aux_sym_parameter_list_repeat1,
  [1542] = 3,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 1,
      sym_identifier,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [1552] = 3,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_parameter_list_repeat1,
  [1562] = 2,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    ACTIONS(227), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1570] = 2,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_parameter_list,
  [1577] = 2,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_function_body,
  [1584] = 1,
    ACTIONS(216), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1589] = 2,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_consequence,
  [1596] = 2,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_function_body,
  [1603] = 2,
    ACTIONS(239), 1,
      anon_sym_LPAREN,
    STATE(65), 1,
      sym_condition,
  [1610] = 2,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    STATE(66), 1,
      sym_parameter_list,
  [1617] = 1,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
  [1621] = 1,
    ACTIONS(243), 1,
      anon_sym_EQ,
  [1625] = 1,
    ACTIONS(245), 1,
      anon_sym_LBRACE,
  [1629] = 1,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
  [1633] = 1,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
  [1637] = 1,
    ACTIONS(251), 1,
      sym_identifier,
  [1641] = 1,
    ACTIONS(253), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 124,
  [SMALL_STATE(6)] = 170,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 262,
  [SMALL_STATE(9)] = 308,
  [SMALL_STATE(10)] = 354,
  [SMALL_STATE(11)] = 400,
  [SMALL_STATE(12)] = 446,
  [SMALL_STATE(13)] = 492,
  [SMALL_STATE(14)] = 517,
  [SMALL_STATE(15)] = 542,
  [SMALL_STATE(16)] = 567,
  [SMALL_STATE(17)] = 592,
  [SMALL_STATE(18)] = 617,
  [SMALL_STATE(19)] = 642,
  [SMALL_STATE(20)] = 667,
  [SMALL_STATE(21)] = 694,
  [SMALL_STATE(22)] = 719,
  [SMALL_STATE(23)] = 747,
  [SMALL_STATE(24)] = 773,
  [SMALL_STATE(25)] = 799,
  [SMALL_STATE(26)] = 825,
  [SMALL_STATE(27)] = 845,
  [SMALL_STATE(28)] = 865,
  [SMALL_STATE(29)] = 887,
  [SMALL_STATE(30)] = 907,
  [SMALL_STATE(31)] = 927,
  [SMALL_STATE(32)] = 947,
  [SMALL_STATE(33)] = 967,
  [SMALL_STATE(34)] = 991,
  [SMALL_STATE(35)] = 1011,
  [SMALL_STATE(36)] = 1031,
  [SMALL_STATE(37)] = 1062,
  [SMALL_STATE(38)] = 1093,
  [SMALL_STATE(39)] = 1124,
  [SMALL_STATE(40)] = 1155,
  [SMALL_STATE(41)] = 1186,
  [SMALL_STATE(42)] = 1209,
  [SMALL_STATE(43)] = 1227,
  [SMALL_STATE(44)] = 1245,
  [SMALL_STATE(45)] = 1270,
  [SMALL_STATE(46)] = 1295,
  [SMALL_STATE(47)] = 1320,
  [SMALL_STATE(48)] = 1345,
  [SMALL_STATE(49)] = 1370,
  [SMALL_STATE(50)] = 1387,
  [SMALL_STATE(51)] = 1406,
  [SMALL_STATE(52)] = 1423,
  [SMALL_STATE(53)] = 1448,
  [SMALL_STATE(54)] = 1465,
  [SMALL_STATE(55)] = 1490,
  [SMALL_STATE(56)] = 1506,
  [SMALL_STATE(57)] = 1520,
  [SMALL_STATE(58)] = 1532,
  [SMALL_STATE(59)] = 1542,
  [SMALL_STATE(60)] = 1552,
  [SMALL_STATE(61)] = 1562,
  [SMALL_STATE(62)] = 1570,
  [SMALL_STATE(63)] = 1577,
  [SMALL_STATE(64)] = 1584,
  [SMALL_STATE(65)] = 1589,
  [SMALL_STATE(66)] = 1596,
  [SMALL_STATE(67)] = 1603,
  [SMALL_STATE(68)] = 1610,
  [SMALL_STATE(69)] = 1617,
  [SMALL_STATE(70)] = 1621,
  [SMALL_STATE(71)] = 1625,
  [SMALL_STATE(72)] = 1629,
  [SMALL_STATE(73)] = 1633,
  [SMALL_STATE(74)] = 1637,
  [SMALL_STATE(75)] = 1641,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(25),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(68),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(27),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(54),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 4),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 4),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(61),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [241] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
